### PR TITLE
Add node-debug plugin into nodejs stacks with debug configuration

### PR DESCRIPTION
**Pull request by svor**
Signed-off-by: svor <vsvydenk@redhat.com>

### What does this PR do?
Adds node-debug plugin into stacks with node debug configuration

Depends on https://github.com/eclipse/che-plugin-registry/pull/506

### What issues does this PR fix or reference?
https://issues.redhat.com/browse/CRW-997

### CODE REVIEW

**Comment by tsmaeder** [comment]
@svor if we _always_ need both extensions, would it make sense to include them in the same Che plugin?

**Comment by svor** [comment]
@tsmaeder I don't see any problem to merge these plugins. But they can live separately and it is not necessarily to add node-debug plugin if you don't want to debug the application.
Should i create an issue for that, @ericwill WDYT?

**Comment by tsmaeder** [comment]
@svor sorry, they _are_ in the same Che plugin in the newest version. I was trying to delete my comment, but Github's "eventual consistency" hid it, I guess ;-)

**Comment by svor** [comment]
ah, i thought you meant node-debug + typescript-ls

**Pull request merged**
