### PR TITLE
Set 0.0.0.0 as a host to run Quarkus app

### PR DESCRIPTION
**Pull request by svor**
Signed-off-by: svor <vsvydenk@redhat.com>

### What does this PR do?
Set `0.0.0.0` as a host to run Quarkus app

### Screenshot/screencast of this PR

screenshot-che openshift io-2020 12 18-17_46_17

### What issues does this PR fix or reference?

https://github.com/eclipse/che/issues/18512

### How to test this PR?

Use this factory: https://che.openshift.io/factory?url=https://raw.githubusercontent.com/svor/che-devfile-registry/sv/quarkusFix/devfiles/quarkus/devfile.yaml

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [x] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [x] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [x] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [x] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [x] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [x] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [x] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### CODE REVIEW

**Comment by sunix** [comment]
Maybe better to set as an env variable? so it works also when you start from the terminal?

**Comment by svor** [comment]
@sunix As I see we don't have this issue with native app:
screenshot-che openshift io-2020 12 18-18_11_25

You can try it https://che.openshift.io/factory?url=https://raw.githubusercontent.com/svor/che-devfile-registry/sv/quarkusFix/devfiles/quarkus/devfile.yaml

**Review by benoitf — APPROVED** [review]

**Comment by sunix** [comment]
Still, I think it is better to set that as an environment variable in the container.

**Comment by benoitf** [comment]
https://user-images.githubusercontent.com/436777/102637691-a8357280-4156-11eb-9172-c07f87f474cc.mov

**Comment by svor** [comment]
> @svor Maybe better to set as an env variable? so it works also when you start from the terminal?
QUARKUS_HTTP_HOST

@sunix If we have this value in env variable, we will get a problem with tests:
```
[ERROR] Tests run: 2, Failures: 0, Errors: 1, Skipped: 1, Time elapsed: 5.676 s <<< FAILURE! - in org.acme.getting.started.GreetingResourceTest
[ERROR] org.acme.getting.started.GreetingResourceTest.testHelloEndpoint  Time elapsed: 0.007 s  <<< ERROR!
java.lang.RuntimeException: java.lang.RuntimeException: Failed to start quarkus
Caused by: java.lang.RuntimeException: Failed to start quarkus
Caused by: java.lang.RuntimeException: Unable to start HTTP server
Caused by: java.util.concurrent.ExecutionException: java.net.UnknownHostException: -Dquarkus.http.host=0.0.0.0: Name or service not known
Caused by: java.net.UnknownHostException: -Dquarkus.http.host=0.0.0.0: Name or service not known
```

**Comment by sunix** [comment]
https://che.openshift.io/factory?url=https://gist.github.com/sunix/2cc2daa838d6be27b425216ff25db3c7/raw/1dea9f886d6fb90abf7fe7a4a7c6370b1635a75b/quarkus.devfile.yaml

https://gist.github.com/sunix/2cc2daa838d6be27b425216ff25db3c7#file-quarkus-devfile-yaml-L28-L29

I don't have your error
maybe you are passing `-Dquarkus.http.host=0.0.0.0` and not 0.0.0.0 in your `QUARKUS_HTTP_HOST`

Selection_112

**Review by sunix — APPROVED** [review]

**Pull request merged**
