### PR TITLE
feat(quarkus-didact): adding a vscode-didact guide to the Quarkus get started devfile.

### PR DESCRIPTION
**Pull request by sunix**
### What does this PR do?
Add a didact guide to the Quarkus get started devfile.

### Screenshot/screencast of this PR
Selection_184

### What issues does this PR fix or reference?
Part of https://github.com/eclipse/che/issues/18197

### How to test this PR?
To try it, it needs a Che plugin registry container built from this branch.
This one could be used: `quay.io/sunix/che-devfile-registry@sha256:cceeb59d3e066ebbc657a23429b858167431190d44de5a5def66dacb335f7f35`
For instance:
```
kubectl edit CheCluster/eclipse-che -n che
```
and 
```yaml
devfileRegistryImage: quay.io/sunix/che-devfile-registry@sha256:cceeb59d3e066ebbc657a23429b858167431190d44de5a5def66dacb335f7f35
```
edit: with the offline build:
```yaml
devfileRegistryImage: quay.io/sunix/che-devfile-registry@sha256:3c7c0618db5f64799b59953f27d6305a19efd0f01c68e9be30178362a3caddf0
```

Then start a new workspace with the "Quarkus Rest API" devfile:
Selection_186

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [x] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [x] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [x] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [x] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [x] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [x] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [x] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### CODE REVIEW

**Review by ericwill — DISMISSED** [review]
Nice little hack n hustle project

**Comment by ericwill** [comment]
@sunix build is failing though:

```
Caching project files for devfile devfiles/quarkus/devfile.yaml
yq: Error running jq: ParserError: while parsing a block mapping
  in "devfiles/quarkus/devfile.yaml", line 60, column 7
expected <block end>, but found '<scalar>'
  in "devfiles/quarkus/devfile.yaml", line 60, column 52.
```

**Comment by sunix** [comment]
Should be fixed :)

**Comment by sunix** [comment]
@ericwill still good for you ?

**Review by ericwill — APPROVED** [review]

**Pull request merged**
