### PR TITLE
Update vert.x sample

### PR DESCRIPTION
**Pull request by svor**
### What does this PR do?
Updates vert.x sample

### What issues does this PR fix or reference?
https://github.com/eclipse/che/issues/15314

### CODE REVIEW

**Comment by ibuziuk** [comment]
@svor  could you please also provide an update to the https://github.com/redhat-developer/devfile/tree/master/getting-started/vertx once this PR is merged ?

**Comment by svor** [comment]
> @svor could you please also provide an update to the https://github.com/redhat-developer/devfile/tree/master/getting-started/vertx once this PR is merged ?

@ibuziuk looks like it already uses this sample, so don't need to change it.

**Comment by ibuziuk** [comment]
@svor are the devfiles identical (other than `persistVolumes: 'false'` option) ?

**Comment by svor** [comment]
@ibuziuk they have small differences, but they use the same sample and commands have same logic. Should they be identical?

**Comment by ibuziuk** [comment]
@svor would be greate to make them identical (apart from the `persistVolumes: 'false'` option)

**Pull request merged**
