### PR TITLE
Make java debug port private for all Java devfiles

### PR DESCRIPTION
**Pull request by vitaliy-guliy**
Signed-off-by: Vitaliy Gulyy <vgulyy@redhat.com>

### What does this PR do?
- Adds Java debug port to java container endpoints
- Marks debug port as private to prevent appearing extra notifications when running debug server

### What issues does this PR fix or reference?

https://github.com/eclipse/che/issues/18138

### How to test this PR?

To test changes your Che-Theia must have ports plugin from this PR https://github.com/eclipse/che-theia/pull/875

A devfile to test how it works with Quarkus stack
```
---
apiVersion: 1.0.0
metadata:
  generateName: quarkus-command-mode-
projects:
  -
    name: quarkus-quickstarts
    source:
      type: git
      location: "https://github.com/quarkusio/quarkus-quickstarts.git"
      sparseCheckoutDir: getting-started-command-mode
components:
  - type: cheEditor
    reference: >-
      https://gist.githubusercontent.com/vitaliy-guliy/f51fc177a6bdac3b7ba1c248b466d515/raw/f77b22e383bd9a978328e191238e7b0826340085/meta.yaml
    alias: che-theia
  -
    type: chePlugin
    id: redhat/quarkus-java11/latest
  -
    type: dockerimage
    alias: centos-quarkus-maven
    image: quay.io/eclipse/che-quarkus:nightly
    env:
      - name: JAVA_OPTS
        value: "-XX:MaxRAMPercentage=50.0 -XX:+UseParallelGC -XX:MinHeapFreeRatio=10
          -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90
          -Dsun.zip.disableMemoryMapping=true -Xms20m -Djava.security.egd=file:/dev/./urandom
          -Duser.home=/home/user"
      - name: MAVEN_OPTS
        value: $(JAVA_OPTS)  
    memoryLimit: 4927M
    mountSources: true
    volumes:
      - name: m2
        containerPath: /home/user/.m2
    endpoints:
      - name: 'debug'
        port: 5005
        attributes:
          public: 'false'
  -
    type: dockerimage
    alias: ubi-minimal
    image: 'registry.access.redhat.com/ubi8/ubi-minimal'
    memoryLimit: 32M
    mountSources: true
    command: ['tail']
    args: ['-f', '/dev/null']

commands:
  -
    name: Package
    actions:
      -
        type: exec
        component: centos-quarkus-maven
        command: "mvn package"
        workdir: ${CHE_PROJECTS_ROOT}/quarkus-quickstarts/getting-started-command-mode
  -
    name: Start Development mode (Hot reload + debug)
    actions:
      -
        type: exec
        component: centos-quarkus-maven
        command: >-
          read -p 'Enter your name [Eclipse Che]: ' name;
          name=${name:-'Eclipse Che'};
          set -o xtrace;
          mvn compile quarkus:dev -Dquarkus.args="$name"
        workdir: ${CHE_PROJECTS_ROOT}/quarkus-quickstarts/getting-started-command-mode
  -
    name: Package Native
    actions:
      -
        type: exec
        component: centos-quarkus-maven
        command: "mvn package -Dnative -Dmaven.test.skip"
        workdir: ${CHE_PROJECTS_ROOT}/quarkus-quickstarts/getting-started-command-mode

  -
    name: Start Native
    actions:
      -
        type: exec
        component: ubi-minimal
        command: >-
          read -p 'Enter your name [Eclipse Che]: ' name;
          name=${name:-'Eclipse Che'};
          set -o xtrace;
          ./getting-started-command-mode-1.0-SNAPSHOT-runner $name
        workdir: ${CHE_PROJECTS_ROOT}/quarkus-quickstarts/getting-started-command-mode/target
  -
    name: Attach remote debugger
    actions:
    - type: vscode-launch
      referenceContent: |
        {
          "version": "0.2.0",
          "configurations": [
            {
              "type": "java",
              "request": "attach",
              "name": "Attach to Remote Quarkus App",
              "hostName": "localhost",
              "port": 5005
            }
          ]
        }
```

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [ ] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [ ] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [ ] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [ ] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [ ] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [ ] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### CODE REVIEW

**Review by benoitf — APPROVED** [review]
LGTM

**Comment by vitaliy-guliy** [comment]
[ci-test-devfiles]

**Review by JPinkney — APPROVED** [review]

**Comment by ericwill** [comment]
Will this change affect any happy path tests, i.e. will QE need to be aware of this change in order to adjust their test cases?

**Comment by vitaliy-guliy** [comment]
> Will this change affect any happy path tests, i.e. will QE need to be aware of this change in order to adjust their test cases?

No, it should not affect. The `public: false` poperty will be used by ports plugin https://github.com/eclipse/che-theia/pull/875, which is still not merged into master. At the moment the property is ignored.

**Comment by vitaliy-guliy** [comment]
Was accidentally closed, clicked wrong button

**Comment by benoitf** [comment]
@vitaliy-guliy you can skip the ci.centos.org check that is not working for months

**Comment by vitaliy-guliy** [comment]
> @vitaliy-guliy you can skip the ci.centos.org check that is not working for months

Ok, merging then.

**Pull request merged**
