### PR TITLE
feat(alpine): Change parent image to be alpine based as well

### PR DESCRIPTION
**Pull request by benoitf**
### What does this PR do?

It replaces centos/httpd with alpine/httpd allowing to be smaller/updated and also multi-arch

Change-Id: I3b9802799fcd05bb388b4fcd3ffa14a6424a8a9e
Signed-off-by: Florent Benoit <fbenoit@redhat.com>

### CODE REVIEW

**Comment by nickboldt** [comment]
Kinda wish we used UBI here so that we didn't have to maintain two radically different dockerfiles but *shrug-emoji* at least we have rhel.Dockerfile to sync with downstream.

Once the registries switch to being OOTB offline mode (in order to work with OCP 4.3+ & include digests) ... then the size difference between alpine and UBI might be negligible.

WDYT?

**Comment by benoitf** [comment]
offline mode is not the default so size still count

**Comment by nickboldt** [comment]
> offline mode is not the default so size still count

Yes, agreed TODAY. But what happens when we move Che to including digests? 

https://github.com/eclipse/che/issues/15350

**Comment by benoitf** [comment]
I don't see what it's changing except replacing tags by the digests in meta.yaml ?

**Comment by benoitf** [comment]
@ericwill @rhopp is it ok for you ?

**Comment by rhopp** [comment]
Fine with me.

**Pull request merged**
