### PR TITLE
use generateName instead of just name

### PR DESCRIPTION
**Pull request by sparkoo**
Signed-off-by: Michal Vala <mvala@redhat.com>

### What does this PR do?
updates devfiles to use `generateName` instead of just name.
Targeted to v7.1.0

### What issues does this PR fix or reference?
https://github.com/eclipse/che/issues/13794
merge after this PR https://github.com/eclipse/che/pull/14157 !!!

### CODE REVIEW

**Comment by sparkoo** [comment]
@l0rd yes. Current implementation in https://github.com/eclipse/che/pull/14157 is without programmed separator and that's how Kubernetes do it. We can do it with separator and I think it would be cleaner. What do you think @sleshchenko @skabashnyuk @benoitf ?

**Comment by skabashnyuk** [comment]
I would stay to k8s api as close as possible.  For example. https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/ . That means if a user wants "-" he has to explicitly add it.

**Comment by sleshchenko** [comment]
@sparkoo I'm OK with the current implementation where a user should include separator in `generateName` if he needs it (K8s API style).

**Comment by benoitf** [comment]
I prefer k8s implementation (but only update doc saying that it's ```[generateName]YYYYY``` and not `[generateName]-YYYYY`)

BTW we could still use in examples generateName without a leading dash as well

as a user I mostly don't care to have for my workspace named `che1234` or `che-1234`or che_1234`

but also in k8s examples most of generateName have leading `-`

**Pull request merged**
