### PR TITLE
fix(quarkus-devfiles): Limit the quarkus native compilation memory limits so it doesn't fail when it reaches the container limit

### PR DESCRIPTION
**Pull request by sunix**
### What does this PR do?
It avoid the compilation to fail if it is reaching the memoryLimit defined for the container.

### What issues does this PR fix or reference?
https://github.com/eclipse/che/issues/17138

### How to test this PR?
- Command mode: https://che.openshift.io/factory?url=https://github.com/sunix/che-devfile-registry/raw/limitMemoryUsageForNativeBuild/devfiles/quarkus-command-mode/devfile.yaml
- Rest API: https://che.openshift.io/factory?url=https://github.com/sunix/che-devfile-registry/raw/limitMemoryUsageForNativeBuild/devfiles/quarkus/devfile.yaml

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [x] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [x] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [x] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [x] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [x] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [x] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [x] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### CODE REVIEW

**Review by benoitf — APPROVED** [review]
image

**Comment by apupier** [comment]
With the Rest example, i still have the error:

```
[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:1.10.3.Final:native-image (default) on project getting-started: Failed to generate native image: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[ERROR]         [error]: Build step io.quarkus.deployment.pkg.steps.JarResultBuildStep#buildNativeImageJar threw an exception: java.lang.IllegalStateException: java.io.IOException: Failed to create a new filesystem for jar:file:/projects/quarkus-quickstarts/getting-started/target/getting-started-1.0-SNAPSHOT-native-image-source-jar/getting-started-1.0-SNAPSHOT-runner.jar
[ERROR]         at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:981)
[ERROR]         at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
[ERROR]         at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
[ERROR]         at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2046)
[ERROR]         at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1578)
[ERROR]         at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
[ERROR]         at java.base/java.lang.Thread.run(Thread.java:834)
[ERROR]         at org.jboss.threads.JBossThread.run(JBossThread.java:479)
[ERROR] Caused by: java.io.IOException: Failed to create a new filesystem for jar:file:/projects/quarkus-quickstarts/getting-started/target/getting-started-1.0-SNAPSHOT-native-image-source-jar/getting-started-1.0-SNAPSHOT-runner.jar
[ERROR]         at io.quarkus.bootstrap.util.ZipUtils.newFileSystem(ZipUtils.java:167)
[ERROR]         at io.quarkus.bootstrap.util.ZipUtils.newZip(ZipUtils.java:116)
[ERROR]         at io.quarkus.deployment.pkg.steps.JarResultBuildStep.buildNativeImageThinJar(JarResultBuildStep.java:755)
[ERROR]         at io.quarkus.deployment.pkg.steps.JarResultBuildStep.buildNativeImageJar(JarResultBuildStep.java:732)
[ERROR]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR]         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR]         at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[ERROR]         at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:972)
[ERROR]         ... 7 more
[ERROR] Caused by: java.util.zip.ZipException: zip END header not found
[ERROR]         at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.zerror(ZipFileSystem.java:1752)
[ERROR]         at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.findEND(ZipFileSystem.java:1047)
[ERROR]         at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.initCEN(ZipFileSystem.java:1056)
[ERROR]         at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.<init>(ZipFileSystem.java:130)
[ERROR]         at jdk.zipfs/jdk.nio.zipfs.ZipFileSystemProvider.newFileSystem(ZipFileSystemProvider.java:109)
[ERROR]         at java.base/java.nio.file.FileSystems.newFileSystem(FileSystems.java:337)
[ERROR]         at java.base/java.nio.file.FileSystems.newFileSystem(FileSystems.java:286)
[ERROR]         at io.quarkus.bootstrap.util.ZipUtils.newFileSystem(ZipUtils.java:160)
[ERROR]         ... 15 more
```

**Comment by benoitf** [comment]
@apupier need to run package before package native

**Comment by sunix** [comment]
@apupier this is very strange. Same thing in ephemeral mode ?

**Comment by sunix** [comment]
normally it is not needed to run package before

**Comment by apupier** [comment]
I relaunched the `package native` a second time in the same workspace (without calling `package`) and it worked.
So I would say the Out of memory error is fixed and there is another one.

**Comment by sunix** [comment]
maybe this is related to the storage. I would say that we would get rid of that when will be in the new dev sandbox

**Comment by sunix** [comment]
@apupier ok to merge ?

**Review by apupier — APPROVED** [review]
ok to merge

**Review by svor — APPROVED** [review]
Tested on che.openshift.io
screenshot-che openshift io-2020 12 10-12_27_06
screenshot-che openshift io-2020 12 10-12_17_15

**Pull request merged**
