### PR TITLE
Add python 3.8 base image

### PR DESCRIPTION
**Pull request by tsmaeder**
### What does this PR do?
Adds a base image for python devfiles using python 3.8.6

### What issues does this PR fix or reference?
https://github.com/eclipse/che/issues/16183

### CODE REVIEW

**Review by JPinkney — APPROVED** [review]

**Review by svor — APPROVED** [review]

**Review by ericwill — APPROVED** [review]
[Quay repo created](https://quay.io/repository/eclipse/che-python-3.8?tag=latest&tab=tags)

**Comment by tsmaeder** [comment]
@ericwill  so how do I get that base image built & pushed?

**Comment by benoitf** [comment]
@tsmaeder images are built and pushed automatically by nightly job of che-devfile-registry
https://ci.centos.org/job/devtools-che-devfile-registry-nightly

but it seems the job did not succeed: https://ci.centos.org/job/devtools-che-devfile-registry-nightly/918/console so...

**Comment by tsmaeder** [comment]
Well, that does not look like an error that would be caused by my change.

**Comment by benoitf** [comment]
https://bugs.centos.org/view.php?id=17781

**Comment by tsmaeder** [comment]
[ci-test-devfiles]

**Comment by tsmaeder** [comment]
[ci-test-devfiles]

**Pull request merged**
