### PR TITLE
Remove debug task in Camel stack eclipse/che#14003

### PR DESCRIPTION
**Pull request by apupier**
- cannot make it working even when attaching manually the Java debugger
afterwise
- Debug is available through CodeLens on the Application Java class
- no other devfiles are providing this kind of debug task

Signed-off-by: Aurélien Pupier <apupier@redhat.com>

### CODE REVIEW

**Comment by apupier** [comment]
please note that in constrained environments, this other PR will need to be merged too https://github.com/eclipse/che-devfile-registry/pull/46

**Comment by l0rd** [comment]
Same as in https://github.com/eclipse/che-devfile-registry/pull/46#issuecomment-514801504

+1 to merge

**Comment by l0rd** [comment]
@apupier c.f. https://github.com/eclipse/che-devfile-registry/blob/master/devfiles/python-django/devfile.yaml#L59

**Comment by slemeur** [comment]
fixing eclipse/che#14003

**Comment by amisevsk** [comment]
It's necessary to add a debug launch config to Theia for debugging to work; I'll look into it more but +1 to merge in the meantime.

**Comment by l0rd** [comment]
@apupier please merge when you are ready

**Pull request merged**
