### PR TITLE
Update offline registry endpoint env var to not mention https

### PR DESCRIPTION
**Pull request by amisevsk**
### What does this PR do?
Change environment variable for offline public endpoint to `CHE_DEVFILE_HTTP_ENDPOINT` instead of HTTPS since it is confusing.

### CODE REVIEW

**Comment by amisevsk** [comment]
cc: @tomgeorge

**Comment by tomgeorge** [comment]
On the operator side I changed the env var to `CHE_DEVFILE_REGISTRY_URL` per @skabashnyuk 's comment.  Can you change to match?

**Comment by ibuziuk** [comment]
Ah, those problems with env var naming... 
I would opt for CHE_DEVFILE_REGISTRY_URL / CHE_DEVFILE_REGISTRY_ENDPOINT

**Comment by tomgeorge** [comment]
thanks! :bowing_man:

**Pull request merged**
